version: '3'

services:
  db:
    image: mysql:latest
    container_name: perfume_db
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    networks:
      - perfume_network

  api:
    container_name: perfume_api
    build:
      context: .
      dockerfile: Dockerfile.dev.api
    ports:
      - '8080:8080'
    networks:
      - perfume_network

networks:
  perfume_network:
