spring:
  config:
    activate:
      on-profile: 'dev'
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: ''
    username: ''
    password: ''

whitelist:
  cors:
    - http://localhost:3000
