spring:
  config:
    activate:
      on-profile: 'default'
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://localhost:3307/test'
    username: 'test'
    password: 'test'
    hikari:
      maximum-pool-size: 5
      max-lifetime: 1800000
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 15000
      leak-detection-threshold: 60000
      pool-name: 'perfume-db-pool'
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: '554827564259-e8ani4u8r08sd313o6sd14a5lughrj82.apps.googleusercontent.com'
            client-secret: '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'
            scope:
              - profile
              - email

whitelist:
  cors:
    - http://localhost:3000

jwt:
  secret-key: ''
  redirect-uri: ''
  access-token-validity-in-seconds: 0
