on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Setup Java 19
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '19'

      - name: Build with Gradle
        run: ./gradlew :perfume-core:clean :perfume-api:clean :perfume-api:build
